Go & Go-postgres: Support 1.21 and drop buster
devcontainers/templates pull request #194
Opened 2023-08-11 04:19 UTC by whuwxl

This PR updates Go to version 1.21 and removes 'buster' from golang tags, following upstream's drop of 'buster' support. Ref: https://github.com/docker-library/golang/commit/cd607138e461368506a6ba50be2163a09b93dab5

2023-08-11 04:23 UTC, whuwxl commented
@microsoft-github-policy-service agree

2023-08-11 20:48 UTC, samruddhikhandale requested changes
Thanks for taking the time to contribute this PR, appreciate it ❇️ 
left some comments!

2023-08-11 20:48 UTC, samruddhikhandale commented on src/go-postgres/devcontainer-template.json
> +                "1.21-bookworm",
Unfortunately, this is in progress. We need to wait for https://github.com/devcontainers/images/pull/701 to be merged in and the images need to be released for this variant.

2023-08-11 20:48 UTC, samruddhikhandale commented on src/go-postgres/devcontainer-template.json
>                  "1.19-bookworm",
Can we remove this as well?

2023-08-11 20:48 UTC, samruddhikhandale commented on src/go-postgres/devcontainer-template.json
> +                "1.19-bullseye"
1.19 has reached EOL and is deprecated. See https://github.com/docker-library/golang/pull/479

2023-08-11 20:48 UTC, samruddhikhandale commented on src/go-postgres/devcontainer-template.json
>              "default": "1.20-bullseye"
```suggestion
            "default": "1.21-bullseye"
```

2023-08-11 20:48 UTC, samruddhikhandale commented on src/go-postgres/devcontainer-template.json
>      "publisher": "Dev Container Spec Maintainers",
Can we bump the major version? Thanks! 

https://github.com/devcontainers/templates/blob/c2361536659318af8637b8726e732c95b039f5e6/src/go-postgres/devcontainer-template.json#L3

2023-08-11 20:48 UTC, samruddhikhandale commented on src/go/devcontainer-template.json
>      "licenseURL": "https://github.com/devcontainers/templates/blob/main/LICENSE",
Can we address the same ^^ comments for this Template as well? Thanks!

2023-08-11 20:48 UTC, samruddhikhandale commented on src/go-postgres/devcontainer-template.json
>              "description": "Go version (use -bookworm, or -bullseye variants on local arm64/Apple Silicon):",
```suggestion
            "description": "Go version:",
```

I believe it's safe to remove this comment, as there are no other variants options available

2023-08-11 23:38 UTC, samruddhikhandale reviewed
PR is in great shape, thanks! 
I'd help approve once the dev container images are released. Dev tags are getting pushed, hoping to release the prod tags on Monday.

2023-08-11 23:44 UTC, whuwxl commented
@samruddhikhandale Thanks a bunch for diving into my PR and sharing your valuable feedback! I've picked up some great insights from it. 😄👍

2023-08-15 17:24 UTC, samruddhikhandale approved these changes
🚢 ⚡

2023-08-15 17:24 UTC, merged