[anaconda] - bookworm released changes
devcontainers/templates pull request #269
Opened 2024-07-10 21:26 UTC by gauravsaini04

**Template Name**

* Anaconda

**Description**

* This PR changes the `major version` number for `anaconda's` template

**_changelog_**

Updated `Dockerfile` for `Anaconda's` template

2024-07-11 19:05 UTC, samruddhikhandale requested changes

2024-07-11 19:05 UTC, samruddhikhandale commented on src/anaconda-postgres/.devcontainer/Dockerfile
> +FROM mcr.microsoft.com/devcontainers/anaconda:1-3
Can we bump Template versions?

2024-07-12 06:54 UTC, gauravsaini04 commented on src/anaconda-postgres/.devcontainer/Dockerfile
> +FROM mcr.microsoft.com/devcontainers/anaconda:1-3
done 👍

2024-07-12 22:47 UTC, samruddhikhandale approved these changes

2024-07-12 22:47 UTC, merged