[cpp]- buster eol changes
devcontainers/templates pull request #271
Opened 2024-07-12 07:21 UTC by gauravsaini04

**Template Name**

*CPP

**Changes**

*Buster - EOL - changes

2024-07-12 22:03 UTC, samruddhikhandale requested changes

2024-07-15 01:52 UTC, gauravsaini04 commented on src/cpp-mariadb/devcontainer-template.json
>  				"debian-12",
done

2024-07-15 01:52 UTC, gauravsaini04 commented on src/cpp/devcontainer-template.json
>                  "debian-11",
done

2024-07-16 20:37 UTC, samruddhikhandale approved these changes

2024-07-16 20:37 UTC, merged