[dotnet] - ubuntu-noble - addition
devcontainers/templates pull request #276
Opened 2024-08-08 02:46 UTC by gauravsaini04

**Template Name**
* dotnet, dotnet-mssql, dotnet-postgres

**_Changelog_**
* added `ubuntu-noble` variant to the list of supported variants

**Checklist**
* [x] checked that applied changes work as expected

2024-08-22 17:41 UTC, samruddhikhandale requested changes

2024-08-22 17:41 UTC, samruddhikhandale commented on src/dotnet-mssql/devcontainer-template.json
> +                "7.0-noble",
Remove the deprecated ones?

2024-08-23 10:30 UTC, gauravsaini04 commented on src/dotnet-mssql/devcontainer-template.json
> +                "8.0-noble",
ok

2024-08-23 23:32 UTC, samruddhikhandale approved these changes
Thanks!

2024-08-23 23:32 UTC, merged