EOL Python 3.8
devcontainers/templates pull request #305
Opened 2024-11-26 16:57 UTC by Kaniska244

2024-12-19 14:21 UTC, chrmarti approved these changes
Thanks!

2024-12-19 14:23 UTC, chrmarti commented
Should we also increment the major version?

2025-03-17 17:35 UTC, eljog requested changes
Version bump?

2025-03-18 16:09 UTC, eljog approved these changes

2025-03-18 16:10 UTC, merged